services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://mongo:27017/localizados_venezuela
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    command: ["--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
